# Generated by Django 3.2.12 on 2022-03-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kerdes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerdes', models.CharField(max_length=255)),
                ('helyesvalasz', models.CharField(max_length=255)),
                ('rosszvalasz1', models.CharField(max_length=255)),
                ('rosszvalasz2', models.CharField(max_length=255)),
                ('rosszvalasz3', models.CharField(max_length=255)),
                ('szam', models.IntegerField()),
                ('logikai', models.BooleanField()),
                ('valosszam', models.FloatField()),
                ('hosszuszoveg', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('hulyeseg', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kérdés',
                'verbose_name_plural': 'Kérdések',
            },
        ),
    ]
